### PR TITLE
Update dependencies, fix vulnerabilities

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@aarongranick-okta Does this PR need to be moved to a DevEx person's account so the tests pass?

**Comment by aarongranick-okta** [comment]
@mraible In order to pass it will need to be on a branch (not a fork). But in this case I think it will fail because of a regression introduced in `okta-react@3.0.5`, we are in the process of releasing a fix. I think the tests should fail if run locally. The error is that the login page is always shown even on the unauthenticated home page.

**Comment by mraible** [comment]
@aarongranick-okta I did have all the tests passing locally with okta-react@3.0.4. When I upgraded to 3.0.6, I saw the error you're talking about. Are you sure it's fixed in 3.0.6? 

As far as branch versus fork, I don't have permission to create a branch and push to this repo.

**Comment by swiftone** [comment]
okta-react 3.0.6 doesn't fix it, 3.0.7 does, which is currently wending it's way through the internal CI before it can be published.

I've copied this over to #136 so it can run tests with the right permissions.

**Comment by aarongranick-okta** [comment]
@mraible The issue is *not* fixed in 3.0.6, we are releasing a 3.0.7 today to fix it. A workaround is to wrap all routes in the <Switch/> component

**Pull request closed without merging**
